"""Alignment service for temporal coordination via Silero VAD plugin"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/alignment.ipynb.

# %% auto #0
__all__ = ['AlignmentService', 'check_alignment_ready']

# %% ../../nbs/services/alignment.ipynb #d5c7f7f2
from typing import List, Dict, Any, Optional
import asyncio

from cjm_plugin_system.core.manager import PluginManager

from ..models import VADChunk

# %% ../../nbs/services/alignment.ipynb #1f748582
class AlignmentService:
    """Service for temporal alignment via Silero VAD plugin."""
    
    def __init__(
        self,
        plugin_manager: PluginManager,  # Plugin manager for accessing VAD plugin
        plugin_name: str = "cjm-media-plugin-silero-vad"  # Name of the VAD plugin
    ):
        """Initialize the alignment service."""
        self._manager = plugin_manager
        self._plugin_name = plugin_name
    
    def is_available(self) -> bool:  # True if plugin is loaded and ready
        """Check if the VAD plugin is available."""
        return self._manager.get_plugin(self._plugin_name) is not None
    
    def ensure_loaded(
        self,
        config: Optional[Dict[str, Any]] = None  # Optional plugin configuration
    ) -> bool:  # True if successfully loaded
        """Ensure the VAD plugin is loaded."""
        if self.is_available():
            return True
        
        # Try to find and load the plugin
        meta = self._manager.get_discovered_meta(self._plugin_name)
        if meta:
            return self._manager.load_plugin(meta, config or {"threshold": 0.5})
        return False
    
    async def analyze_audio_async(
        self,
        media_path: str  # Path to audio/video file
    ) -> tuple[List[VADChunk], float]:  # (VAD chunks, total duration)
        """Analyze audio file and return VAD chunks."""
        if not self.is_available():
            raise RuntimeError(f"Plugin {self._plugin_name} not loaded")
        
        # Execute plugin
        result = await self._manager.execute_plugin_async(
            self._plugin_name,
            media_path=media_path
        )
        
        # Extract ranges and metadata
        ranges = result.get('ranges', [])
        metadata = result.get('metadata', {})
        duration = metadata.get('duration', 0.0)
        
        # Convert to VADChunk objects
        chunks = []
        for idx, r in enumerate(ranges):
            chunk = VADChunk(
                index=idx,
                start_time=r.get('start', r.get('start_time', 0.0)),
                end_time=r.get('end', r.get('end_time', 0.0))
            )
            chunks.append(chunk)
        
        return chunks, duration
    
    def analyze_audio(
        self,
        media_path: str  # Path to audio/video file
    ) -> tuple[List[VADChunk], float]:  # (VAD chunks, total duration)
        """Analyze audio file synchronously."""
        return asyncio.get_event_loop().run_until_complete(
            self.analyze_audio_async(media_path)
        )

# %% ../../nbs/services/alignment.ipynb #xe88wntlhs
def check_alignment_ready(
    segment_count: int,  # Number of text segments
    chunk_count: int,  # Number of VAD chunks
) -> bool:  # True if counts match and alignment can proceed
    """Check if segment and VAD chunk counts match for 1:1 alignment."""
    return segment_count > 0 and chunk_count > 0 and segment_count == chunk_count
