# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-transcript-vad-align',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-transcript-vad-align',
                'lib_path': 'cjm_transcript_vad_align'},
  'syms': {}}
