"""HTML ID constants for Phase 2 Right Column: VAD Alignment"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['AlignmentHtmlIds']

# %% ../nbs/html_ids.ipynb #c3d4e5f6
# Framework-agnostic — no external imports needed

class AlignmentHtmlIds:
    """HTML ID constants for Phase 2 Right Column: VAD Alignment."""

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Column Layout (matches CombinedHtmlIds values for cross-package compatibility)
    COLUMN_CONTENT = "sd-align-column-content"  # Content area ID (used by HTMX swaps)
    MINI_STATS = "sd-align-mini-stats"  # Mini-stats badge ID (used by OOB updates)

    # Components
    # (Card stack IDs provided by CardStackHtmlIds from cjm-fasthtml-card-stack with prefix "sd-align")
    ALIGNMENT_TOOLBAR = "sd-align-toolbar"
    ALIGNMENT_STATS = "sd-align-stats"
    ALIGNMENT_FOOTER = "sd-align-footer"
    SOURCE_POSITION = "sd-align-source-position"  # Audio file position indicator

    @staticmethod
    def vad_chunk(
        index:int  # VAD chunk index
    ) -> str:  # HTML ID for the VAD chunk element
        """Generate HTML ID for a VAD chunk element."""
        return f"sd-vad-chunk-{index}"
