"""Data models and URL bundles for the alignment package"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['AlignmentStepState', 'VADChunk', 'AlignmentUrls']

# %% ../nbs/models.ipynb #align-models-imports
from typing import Optional, List, Dict, Any
from typing_extensions import TypedDict
from dataclasses import dataclass, field, asdict

from cjm_fasthtml_card_stack.core.models import CardStackUrls

# %% ../nbs/models.ipynb #align-models-state
class AlignmentStepState(TypedDict, total=False):
    """State for Phase 2 (right column): Temporal Alignment."""

    # --- Workflow-specific ---
    is_initialized: bool  # Whether VAD data has been fetched
    vad_chunks: List[Dict[str, Any]]  # VAD chunks (serialized VADChunk)
    media_path: Optional[str]  # Path to first audio file (backward compat)
    media_paths: List[str]  # Ordered list of audio file paths
    audio_duration: Optional[float]  # Total audio duration in seconds

    # --- Card stack view state ---
    focused_chunk_index: int  # Currently focused VAD chunk (default 0)
    visible_count: int  # Number of visible cards in viewport
    is_auto_mode: bool  # Whether card count is in auto-adjust mode
    card_width: int  # Card stack width in rem units

# %% ../nbs/models.ipynb #align-models-chunk
@dataclass
class VADChunk:
    """A voice activity detection time range."""
    
    index: int  # Chunk index in sequence (global across all audio files)
    start_time: float  # Start time in seconds (relative to its audio file)
    end_time: float  # End time in seconds (relative to its audio file)
    audio_file_index: int = 0  # Which audio file this chunk belongs to
    
    @property
    def duration(self) -> float:  # Duration in seconds
        """Calculate chunk duration."""
        return self.end_time - self.start_time
    
    def to_dict(self) -> Dict[str, Any]:  # Dictionary representation
        """Convert to dictionary for JSON serialization."""
        return asdict(self)
    
    @classmethod
    def from_dict(
        cls,
        data: Dict[str, Any]  # Dictionary representation
    ) -> "VADChunk":  # Reconstructed VADChunk
        """Create from dictionary."""
        data = data.copy()
        # Remove legacy fields if present
        data.pop("assigned_segment", None)
        # Default audio_file_index for backward compat
        if "audio_file_index" not in data:
            data["audio_file_index"] = 0
        return cls(**data)

# %% ../nbs/models.ipynb #align-models-urls
@dataclass
class AlignmentUrls:
    """URL bundle for Phase 2 alignment route handlers and renderers."""

    # Card stack navigation and viewport (from cjm-fasthtml-card-stack library)
    card_stack: CardStackUrls = field(default_factory=CardStackUrls)

    # Workflow-specific: initialization
    init: str = ""  # Initialize alignment (fetch VAD data)

    # Audio serving
    audio_src: str = ""  # Audio file serving URL base
