"""Time formatting utilities for VAD alignment display"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['format_time_precise']

# %% ../nbs/utils.ipynb #align-utils-imports
from typing import Optional

# %% ../nbs/utils.ipynb #align-utils-format-time-precise
def format_time_precise(
    seconds: Optional[float]  # Time in seconds
) -> str:  # Formatted time string (m:ss.s)
    """Format seconds as m:ss.s for sub-second display."""
    if seconds is None:
        return "-:--.-"
    minutes = int(seconds // 60)
    secs = seconds % 60
    return f"{minutes}:{secs:04.1f}"
