"""Time formatting utilities for VAD alignment display"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['format_time_precise', 'get_audio_file_boundaries', 'get_audio_file_count', 'get_audio_file_position']

# %% ../nbs/utils.ipynb #align-utils-imports
from typing import Optional, List, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from cjm_transcript_vad_align.models import VADChunk

# %% ../nbs/utils.ipynb #align-utils-format-time-precise
def format_time_precise(
    seconds: Optional[float]  # Time in seconds
) -> str:  # Formatted time string (m:ss.s)
    """Format seconds as m:ss.s for sub-second display."""
    if seconds is None:
        return "-:--.-"
    minutes = int(seconds // 60)
    secs = seconds % 60
    return f"{minutes}:{secs:04.1f}"

# %% ../nbs/utils.ipynb #jfytfkqdius
def get_audio_file_boundaries(
    chunks: List["VADChunk"],  # Ordered list of VAD chunks
) -> Set[int]:  # Indices where audio_file_index changes from the previous chunk
    """Find indices where audio_file_index changes between adjacent chunks.
    
    A boundary at index N means chunk[N].audio_file_index differs from
    chunk[N-1].audio_file_index.
    """
    boundaries = set()
    for i in range(1, len(chunks)):
        if chunks[i].audio_file_index != chunks[i - 1].audio_file_index:
            boundaries.add(i)
    return boundaries

# %% ../nbs/utils.ipynb #d5pxnidly8
def get_audio_file_count(
    chunks: List["VADChunk"],  # Ordered list of VAD chunks
) -> int:  # Number of unique audio files
    """Count the number of unique audio files in the chunk list."""
    if not chunks:
        return 0
    return len({c.audio_file_index for c in chunks})

# %% ../nbs/utils.ipynb #3w4ujute25e
def get_audio_file_position(
    chunks: List["VADChunk"],  # Ordered list of VAD chunks
    focused_index: int,  # Index of the focused chunk
) -> Optional[int]:  # 1-based position of the audio file, or None
    """Get the audio file position (1-based) of the focused chunk.
    
    Returns which audio file the focused chunk belongs to,
    based on order of first appearance.
    """
    if not chunks or focused_index < 0 or focused_index >= len(chunks):
        return None
    focused_afi = chunks[focused_index].audio_file_index
    seen = []
    for c in chunks:
        if c.audio_file_index not in seen:
            seen.append(c.audio_file_index)
    if focused_afi in seen:
        return seen.index(focused_afi) + 1
    return None
