"""Audio playback controls for the alignment card stack: auto-navigate toggle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/audio_controls.ipynb.

# %% auto #0
__all__ = ['AlignAudioControlIds', 'render_align_auto_navigate_toggle', 'render_align_audio_controls']

# %% ../../nbs/components/audio_controls.ipynb #align-ac-imports
from typing import Any

from fasthtml.common import Div, Span, Input, Label

# DaisyUI components
from cjm_fasthtml_daisyui.components.data_input.toggle import toggle, toggle_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, gap
from cjm_fasthtml_tailwind.core.base import combine_classes

# %% ../../nbs/components/audio_controls.ipynb #align-ac-ids
class AlignAudioControlIds:
    """HTML ID constants for alignment audio control elements."""

    AUTO_NAV_TOGGLE = "sd-align-auto-nav-toggle"
    AUDIO_CONTROLS = "sd-align-audio-controls"

# %% ../../nbs/components/audio_controls.ipynb #align-ac-toggle
def render_align_auto_navigate_toggle(
    enabled:bool=False,  # Whether auto-navigate is enabled
) -> Any:  # Auto-navigate toggle component
    """Render auto-navigate toggle switch for alignment audio (client-side only)."""
    onchange_js = "if(window.setAlignAutoNavigate) window.setAlignAutoNavigate(this.checked);"

    # Only pass checked when enabled (FastHTML renders checked=False as an attribute)
    check_attr = {"checked": True} if enabled else {}

    return Div(
        Label(
            Span(
                "Auto-play:",
                cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
            ),
            Input(
                type="checkbox",
                id=AlignAudioControlIds.AUTO_NAV_TOGGLE,
                name="auto_navigate",
                cls=combine_classes(toggle, toggle_sizes.sm),
                onchange=onchange_js,
                **check_attr,
            ),
            cls=combine_classes(flex_display, items.center)
        ),
        cls=combine_classes(flex_display, items.center)
    )

# %% ../../nbs/components/audio_controls.ipynb #align-ac-container
def render_align_audio_controls(
    auto_navigate:bool=False,  # Whether auto-navigate is enabled
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Combined audio controls component
    """Render alignment audio controls (auto-navigate toggle)."""
    return Div(
        render_align_auto_navigate_toggle(auto_navigate),
        id=AlignAudioControlIds.AUDIO_CONTROLS,
        cls=combine_classes(flex_display, items.center, gap(4)),
        hx_swap_oob="true" if oob else None,
    )
