"""Audio playback controls for the alignment card stack: auto-navigate toggle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/audio_controls.ipynb.

# %% auto #0
__all__ = ['PLAYBACK_SPEEDS', 'AlignAudioControlIds', 'render_align_speed_selector', 'render_align_auto_navigate_toggle',
           'render_align_audio_controls']

# %% ../../nbs/components/audio_controls.ipynb #align-ac-imports
from typing import Any, List

from fasthtml.common import Div, Span, Input, Label, Select, Option

# DaisyUI components
from cjm_fasthtml_daisyui.components.data_input.toggle import toggle, toggle_sizes
from cjm_fasthtml_daisyui.components.data_input.select import select, select_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui, bg_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, gap
from cjm_fasthtml_tailwind.core.base import combine_classes

# Web Audio library — for initial speed sync helper
from cjm_fasthtml_web_audio.models import WebAudioConfig
from cjm_fasthtml_web_audio.components import render_initial_speed_sync

# %% ../../nbs/components/audio_controls.ipynb #align-ac-ids
class AlignAudioControlIds:
    """HTML ID constants for alignment audio control elements."""

    SPEED_SELECT = "sd-align-speed-select"
    AUTO_NAV_TOGGLE = "sd-align-auto-nav-toggle"
    AUDIO_CONTROLS = "sd-align-audio-controls"

# %% ../../nbs/components/audio_controls.ipynb #57cb448c
# Available playback speeds (value, label)
PLAYBACK_SPEEDS: List[tuple] = [
    (0.5, "0.5x"),
    (0.75, "0.75x"),
    (1.0, "1x"),
    (1.25, "1.25x"),
    (1.5, "1.5x"),
    (2.0, "2x"),
    (2.5, "2.5x"),
    (3.0, "3x"),
]

# Config for render_initial_speed_sync — only `namespace` and `enable_speed` are read.
# Defined locally here to avoid a circular import with components.callbacks (which defines
# the full ALIGN_AUDIO_CONFIG but also imports symbols from this module).
_SYNC_CONFIG = WebAudioConfig(
    namespace="align",
    indicator_selector="",
    enable_speed=True,
)

def render_align_speed_selector(
    current_speed:float=1.0,  # Current playback speed
    change_url:str="",  # URL to POST speed changes to (for server persistence)
) -> Any:  # Speed selector component (select + sync script)
    """Render playback speed selector dropdown for alignment audio.
    
    When `current_speed != 1.0`, also emits a sync <Script> that calls
    `window.setAlignSpeed(current_speed)` after insertion. This works around
    `generate_state_init` resetting `playbackSpeed` to 1.0 on every render —
    without the sync, the dropdown visually restores the saved speed but
    the JS state stays at 1.0 until the user interacts with the dropdown.
    """
    options = [
        Option(
            label,
            value=str(speed),
            selected=(speed == current_speed),
        )
        for speed, label in PLAYBACK_SPEEDS
    ]

    # Build HTMX attributes if URL provided
    htmx_attrs = {}
    if change_url:
        htmx_attrs = {
            "hx_post": change_url,
            "hx_trigger": "change",
            "hx_swap": "none",
        }

    # Client-side JS to update playback speed immediately via web audio library
    onchange_js = "if(window.setAlignSpeed) window.setAlignSpeed(parseFloat(this.value));"

    return Div(
        Span(
            "Speed:",
            cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
        ),
        Select(
            *options,
            id=AlignAudioControlIds.SPEED_SELECT,
            name="speed",
            cls=combine_classes(select, select_sizes.sm),
            onchange=onchange_js,
            **htmx_attrs,
        ),
        # Sync JS state to current_speed (no-op when speed == 1.0)
        render_initial_speed_sync(_SYNC_CONFIG, current_speed),
        cls=combine_classes(flex_display, items.center)
    )

# %% ../../nbs/components/audio_controls.ipynb #align-ac-toggle
# CSS classes for toggle state coloring
_TOGGLE_BG_OFF = str(bg_dui.error)    # Red when auto-play disabled
_TOGGLE_BG_ON = str(bg_dui.success)   # Green when auto-play enabled

def _toggle_color_js(toggle_id:str) -> str:  # JS snippet to sync toggle color classes
    """Generate JS to swap bg-error/bg-success on the toggle based on checked state."""
    return (
        f"var _t=document.getElementById('{toggle_id}');"
        f"if(_t){{_t.classList.remove('{_TOGGLE_BG_OFF}','{_TOGGLE_BG_ON}');"
        f"_t.classList.add(_t.checked?'{_TOGGLE_BG_ON}':'{_TOGGLE_BG_OFF}');}}"
    )

def render_align_auto_navigate_toggle(
    enabled:bool=False,  # Whether auto-navigate is enabled
) -> Any:  # Auto-navigate toggle component
    """Render auto-navigate toggle switch for alignment audio (client-side only)."""
    toggle_id = AlignAudioControlIds.AUTO_NAV_TOGGLE
    color_js = _toggle_color_js(toggle_id)
    onchange_js = f"if(window.setAlignAutoNavigate) window.setAlignAutoNavigate(this.checked);{color_js}"

    # Only pass checked when enabled (FastHTML renders checked=False as an attribute)
    check_attr = {"checked": True} if enabled else {}
    color_cls = _TOGGLE_BG_ON if enabled else _TOGGLE_BG_OFF

    return Div(
        Label(
            Span(
                "Auto-play:",
                cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
            ),
            Input(
                type="checkbox",
                id=toggle_id,
                name="auto_navigate",
                cls=combine_classes(toggle, toggle_sizes.sm, color_cls),
                onchange=onchange_js,
                **check_attr,
            ),
            cls=combine_classes(flex_display, items.center)
        ),
        cls=combine_classes(flex_display, items.center)
    )

# %% ../../nbs/components/audio_controls.ipynb #align-ac-container
def render_align_audio_controls(
    current_speed:float=1.0,  # Current playback speed
    auto_navigate:bool=False,  # Whether auto-navigate is enabled
    speed_url:str="",  # URL for speed changes (server persistence)
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Combined audio controls component
    """Render alignment audio controls (speed selector + auto-navigate toggle)."""
    return Div(
        render_align_speed_selector(current_speed, speed_url),
        render_align_auto_navigate_toggle(auto_navigate),
        id=AlignAudioControlIds.AUDIO_CONTROLS,
        cls=combine_classes(flex_display, items.center, gap(4)),
        hx_swap_oob="true" if oob else None,
    )
