"""Focus change callback and audio playback JavaScript for the alignment card stack"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/callbacks.ipynb.

# %% auto #0
__all__ = ['ALIGN_AUDIO_CONFIG', 'generate_align_callbacks_script']

# %% ../../nbs/components/callbacks.ipynb #align-cb-imports
from dataclasses import replace

from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.core.models import CardStackUrls
from cjm_fasthtml_card_stack.js.core import generate_card_stack_js

from cjm_fasthtml_web_audio.models import WebAudioConfig
from cjm_fasthtml_web_audio.js import generate_web_audio_js

from cjm_transcript_vad_align.components.audio_controls import (
    AlignAudioControlIds, _TOGGLE_BG_OFF, _TOGGLE_BG_ON,
)

# %% ../../nbs/components/callbacks.ipynb #align-cb-focus-script
ALIGN_AUDIO_CONFIG = WebAudioConfig(
    namespace="align",
    indicator_selector=".vad-playing-indicator",
    enable_speed=True,
    enable_replay=True,
    enable_auto_nav=True,
)

# %% ../../nbs/components/callbacks.ipynb #y9odapos86c
def _generate_toggle_auto_play_js() -> str:  # JS defining window.toggleAlignAutoPlay
    """Generate JS for the A key auto-play toggle function."""
    tid = AlignAudioControlIds.AUTO_NAV_TOGGLE
    return f"""
    window.toggleAlignAutoPlay = function() {{
        var _t = document.getElementById('{tid}');
        if (!_t || !window.setAlignAutoNavigate) return;
        _t.checked = !_t.checked;
        window.setAlignAutoNavigate(_t.checked);
        _t.classList.remove('{_TOGGLE_BG_OFF}', '{_TOGGLE_BG_ON}');
        _t.classList.add(_t.checked ? '{_TOGGLE_BG_ON}' : '{_TOGGLE_BG_OFF}');
    }};"""

# %% ../../nbs/components/callbacks.ipynb #align-cb-gen
def generate_align_callbacks_script(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs
    config:CardStackConfig,  # Card stack configuration
    urls:CardStackUrls,  # Card stack URL bundle
    container_id:str,  # ID of the alignment container (parent of card stack)
    focus_input_id:str,  # ID of hidden input for focused chunk index
    should_play_fn:str="",  # Consumer-defined play guard function name (overrides default zone guard)
) -> any:  # Script element with all JavaScript callbacks
    """Generate JavaScript for alignment card stack with Web Audio API audition."""
    # Use consumer-provided play guard if specified, otherwise use default config
    audio_config = ALIGN_AUDIO_CONFIG
    if should_play_fn:
        audio_config = replace(ALIGN_AUDIO_CONFIG, should_play_fn=should_play_fn)

    web_audio_js = generate_web_audio_js(
        config=audio_config,
        focus_input_id=focus_input_id,
        card_stack_id=ids.card_stack,
        nav_down_btn_id=button_ids.nav_down,
    )

    # Auto-play toggle function for A key
    toggle_js = _generate_toggle_auto_play_js()

    return generate_card_stack_js(
        ids=ids,
        button_ids=button_ids,
        config=config,
        urls=urls,
        container_id=container_id,
        extra_scripts=(web_audio_js, toggle_js),
    )
