"""Focus change callback and audio playback JavaScript for the alignment card stack"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/callbacks.ipynb.

# %% auto #0
__all__ = ['ALIGN_AUDIO_CONFIG', 'generate_align_callbacks_script']

# %% ../../nbs/components/callbacks.ipynb #align-cb-imports
from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.core.models import CardStackUrls
from cjm_fasthtml_card_stack.js.core import generate_card_stack_js

from cjm_fasthtml_web_audio.models import WebAudioConfig
from cjm_fasthtml_web_audio.js import generate_web_audio_js

# %% ../../nbs/components/callbacks.ipynb #align-cb-focus-script
ALIGN_AUDIO_CONFIG = WebAudioConfig(
    namespace="align",
    indicator_selector=".vad-playing-indicator",
)

# %% ../../nbs/components/callbacks.ipynb #align-cb-gen
def generate_align_callbacks_script(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs
    config:CardStackConfig,  # Card stack configuration
    urls:CardStackUrls,  # Card stack URL bundle
    container_id:str,  # ID of the alignment container (parent of card stack)
    focus_input_id:str,  # ID of hidden input for focused chunk index
) -> any:  # Script element with all JavaScript callbacks
    """Generate JavaScript for alignment card stack with Web Audio API audition."""
    web_audio_js = generate_web_audio_js(
        config=ALIGN_AUDIO_CONFIG,
        focus_input_id=focus_input_id,
        card_stack_id=ids.card_stack,
    )

    return generate_card_stack_js(
        ids=ids,
        button_ids=button_ids,
        config=config,
        urls=urls,
        container_id=container_id,
        extra_scripts=(web_audio_js,),
    )
