"""Card stack configuration, HTML IDs, and button IDs for the VAD alignment card stack"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/card_stack_config.ipynb.

# %% auto #0
__all__ = ['ALIGN_CS_CONFIG', 'ALIGN_CS_IDS', 'ALIGN_CS_BTN_IDS']

# %% ../../nbs/components/card_stack_config.ipynb #align-csc-exports
from cjm_fasthtml_card_stack.core.config import CardStackConfig, CardStackStyleConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds

# %% ../../nbs/components/card_stack_config.ipynb #align-csc-config
ALIGN_CS_CONFIG = CardStackConfig(
    prefix="sd-align",
    card_width_min=20,       # Narrower range for compact cards
    card_width_max=60,
    card_width_step=5,
    style=CardStackStyleConfig(
        section_gap="0.75rem",     # Tighter spacing for compact cards
        slot_padding="0.125rem",
        viewport_padding_x='0.0rem', 
        viewport_padding_y='0.0rem'
    ),
)

ALIGN_CS_IDS = CardStackHtmlIds(prefix=ALIGN_CS_CONFIG.prefix)
ALIGN_CS_BTN_IDS = CardStackButtonIds(prefix=ALIGN_CS_CONFIG.prefix)
