"""Alignment-specific keyboard building blocks for assembly into a shared ZoneManager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/keyboard_config.ipynb.

# %% auto #0
__all__ = ['create_align_kb_parts']

# %% ../../nbs/components/keyboard_config.ipynb #align-kb-imports
from typing import Tuple

# Keyboard navigation library
from cjm_fasthtml_keyboard_navigation.core.focus_zone import FocusZone

# Card stack library
from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.keyboard.actions import (
    create_card_stack_focus_zone, create_card_stack_nav_actions,
)

# %% ../../nbs/components/keyboard_config.ipynb #align-kb-parts
def create_align_kb_parts(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs for navigation
    config:CardStackConfig,  # Card stack configuration
) -> Tuple[FocusZone, tuple, tuple]:  # (zone, actions, modes)
    """Create alignment-specific keyboard building blocks."""
    # Card stack zone from library
    # Note: No data_attributes needed — onAlignFocusChange callback manually updates the
    # card stack hidden input and reads start/end times directly from card DOM elements
    card_zone = create_card_stack_focus_zone(
        ids=ids,
        on_focus_change="onAlignFocusChange",
    )

    # Card stack navigation actions from library (arrows, page jump, first/last, width)
    nav_actions = create_card_stack_nav_actions(
        zone_id=card_zone.id,
        button_ids=button_ids,
        config=config,
    )

    # Alignment has only navigation actions (no undo, no split mode)
    actions = nav_actions
    modes = ()  # No sub-modes — alignment uses a single navigation mode

    return card_zone, actions, modes
