"""Composable render functions for the alignment card stack column"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/step_renderer.ipynb.

# %% auto #0
__all__ = ['DEBUG_ALIGN_RENDER', 'render_align_toolbar', 'render_align_stats', 'render_align_column_body',
           'render_align_footer_content', 'render_align_mini_stats_text']

# %% ../../nbs/components/step_renderer.ipynb #align-sr-imports
from typing import Any, List, Optional

from fasthtml.common import Div, Span, Audio

# DaisyUI components
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, h, min_h
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.layout import overflow, display_tw
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, justify, items, gap, grow
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Card stack library
from cjm_fasthtml_card_stack.components.viewport import render_viewport
from cjm_fasthtml_card_stack.components.controls import render_card_count_select
from cjm_fasthtml_card_stack.components.progress import render_progress_indicator
from cjm_fasthtml_card_stack.core.models import CardStackState
from cjm_fasthtml_card_stack.core.constants import DEFAULT_VISIBLE_COUNT, DEFAULT_CARD_WIDTH
from cjm_fasthtml_card_stack.keyboard.actions import render_card_stack_action_buttons

# Alignment configuration (same package)
from cjm_transcript_vad_align.components.card_stack_config import (
    ALIGN_CS_CONFIG, ALIGN_CS_IDS, ALIGN_CS_BTN_IDS,
)

# Local imports (page-specific, no cross-package dependencies)
from ..html_ids import AlignmentHtmlIds
from ..models import VADChunk, AlignmentUrls
from cjm_transcript_vad_align.components.vad_card import (
    create_vad_card_renderer
)
from cjm_transcript_vad_align.components.callbacks import (
    generate_align_callbacks_script
)

# Debug flag for alignment rendering tracing (set False in production)
DEBUG_ALIGN_RENDER = False

# %% ../../nbs/components/step_renderer.ipynb #align-sr-toolbar
def render_align_toolbar(
    visible_count:int=DEFAULT_VISIBLE_COUNT,  # Current visible card count
    is_auto_mode:bool=False,  # Whether card count is in auto-adjust mode
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Toolbar component
    """Render the alignment toolbar with card count selector."""
    return Div(
        # Spacer
        Div(cls=str(grow())),

        # Right: Card count selector
        Div(
            Span(
                "Cards:",
                cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
            ),
            render_card_count_select(
                ALIGN_CS_CONFIG, ALIGN_CS_IDS,
                current_count=visible_count,
                is_auto_mode=is_auto_mode,
            ),
            cls=combine_classes(flex_display, items.center)
        ),

        id=AlignmentHtmlIds.ALIGNMENT_TOOLBAR,
        cls=combine_classes(flex_display, gap(2), items.center),
        hx_swap_oob="true" if oob else None
    )

# %% ../../nbs/components/step_renderer.ipynb #align-sr-stats
def render_align_stats(
    chunks:List[VADChunk],  # Current VAD chunks
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Statistics component
    """Render alignment statistics."""
    total = len(chunks)
    total_dur = sum(c.duration for c in chunks) if chunks else 0.0

    return Div(
        Span(
            f"{total} chunks \u00b7 {total_dur:.1f}s total",
            cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70))
        ),
        id=AlignmentHtmlIds.ALIGNMENT_STATS,
        hx_swap_oob="true" if oob else None
    )


# %% ../../nbs/components/step_renderer.ipynb #align-sr-body
def render_align_column_body(
    chunks:List[VADChunk],  # VAD chunks to display
    focused_index:int,  # Currently focused chunk index
    visible_count:int,  # Number of visible cards in viewport
    card_width:int,  # Card stack width in rem
    urls:AlignmentUrls,  # URL bundle for alignment routes
    kb_system:Any=None,  # Rendered keyboard system (None when KB managed externally)
    media_path:Optional[str]=None,  # Path to audio file for playback
) -> Any:  # Div with id=COLUMN_CONTENT
    """Render the alignment column content area with card stack viewport."""
    if DEBUG_ALIGN_RENDER:
        print(f"[ALIGN_RENDER] render_align_column_body called")
        print(f"[ALIGN_RENDER] chunks count: {len(chunks)}")
        print(f"[ALIGN_RENDER] media_path: {media_path}")
        print(f"[ALIGN_RENDER] urls.audio_src: {urls.audio_src if urls else None}")

    # Create card renderer callback
    card_renderer = create_vad_card_renderer()

    # Build CardStackState for library viewport
    cs_state = CardStackState(
        focused_index=focused_index,
        visible_count=visible_count,
        card_width=card_width,
    )

    # Render viewport from library
    viewport = render_viewport(
        card_items=chunks,
        state=cs_state,
        config=ALIGN_CS_CONFIG,
        ids=ALIGN_CS_IDS,
        urls=urls.card_stack,
        render_card=card_renderer,
        form_input_name="chunk_index",
    )

    # Build audio source URL
    audio_src = ""
    if urls.audio_src and media_path:
        audio_src = f"{urls.audio_src}?path={media_path}"

    if DEBUG_ALIGN_RENDER:
        print(f"[ALIGN_RENDER] constructed audio_src: '{audio_src}'")

    # Generate JS: library card stack JS + audio focus change callback.
    # container_id is the column CONTENT area (COLUMN_CONTENT), which is
    # the immediate parent of the card stack. The column header is accounted for
    # by containerTop (content area starts below the header). This ensures the
    # algorithm only measures actual siblings of the card stack.
    callbacks_script = generate_align_callbacks_script(
        ids=ALIGN_CS_IDS,
        button_ids=ALIGN_CS_BTN_IDS,
        config=ALIGN_CS_CONFIG,
        urls=urls.card_stack,
        container_id=AlignmentHtmlIds.COLUMN_CONTENT,
        focus_input_id=ALIGN_CS_IDS.focused_index_input,
        audio_player_id=AlignmentHtmlIds.AUDIO_PLAYER,
    )

    # Keyboard system elements (optional — may be managed at combined-step level)
    kb_elements = ()
    if kb_system is not None:
        kb_elements = (kb_system.script, kb_system.hidden_inputs, kb_system.action_buttons)

    return Div(
        # Card stack viewport
        viewport,

        # Hidden audio element for audition playback
        Audio(
            id=AlignmentHtmlIds.AUDIO_PLAYER,
            src=audio_src,
            preload="metadata",
            cls=str(display_tw.hidden),
        ),

        # Keyboard navigation system (when provided)
        *kb_elements,

        # Hidden action buttons for JS-triggered card stack nav
        render_card_stack_action_buttons(ALIGN_CS_BTN_IDS, urls.card_stack, ALIGN_CS_IDS),

        # JavaScript callbacks (library card stack JS + audio playback)
        callbacks_script,

        id=AlignmentHtmlIds.COLUMN_CONTENT,
        cls=combine_classes(grow(), min_h(0), overflow.hidden, flex_display, flex_direction.col)
    )

# %% ../../nbs/components/step_renderer.ipynb #align-sr-footer
def render_align_footer_content(
    chunks:List[VADChunk],  # Current VAD chunks
    focused_index:int,  # Currently focused chunk index
) -> Any:  # Footer content with progress indicator and stats
    """Render footer content with progress indicator and alignment statistics."""
    total_chunks = len(chunks)

    return Div(
        render_progress_indicator(focused_index, total_chunks, ALIGN_CS_IDS, label="VAD Chunk"),
        render_align_stats(chunks),
        id=AlignmentHtmlIds.ALIGNMENT_FOOTER,
        cls=combine_classes(flex_display, justify.between, items.center, gap(4))
    )

# %% ../../nbs/components/step_renderer.ipynb #align-sr-mini-stats
def render_align_mini_stats_text(
    chunks:List[VADChunk],  # Current VAD chunks
) -> str:  # Compact stats string for column header badge
    """Generate compact stats string for the alignment column header badge."""
    total = len(chunks)
    total_dur = sum(c.duration for c in chunks) if chunks else 0.0
    return f"{total} chunks \u00b7 {total_dur:.1f}s"
