"""Route handlers for alignment audio playback controls"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/audio.ipynb.

# %% auto #0
__all__ = ['init_audio_router']

# %% ../../nbs/routes/audio.ipynb #align-audio-imports
from typing import Dict, Callable, Tuple

from fasthtml.common import APIRouter, Script

from cjm_fasthtml_interactions.core.state_store import get_session_id

from ..models import AlignmentUrls
from cjm_transcript_vad_align.routes.core import (
    WorkflowStateStore, _update_alignment_state
)

# %% ../../nbs/routes/audio.ipynb #align-audio-toggle-js
def _generate_auto_nav_js(
    enabled:bool  # Whether auto-navigate is enabled
) -> str:  # JavaScript to update auto-navigate flag
    """Generate JS to update auto-navigate flag via shared library."""
    enabled_str = "true" if enabled else "false"
    return f"""
        if (window.setAlignAutoNavigate) window.setAlignAutoNavigate({enabled_str});
    """

def _generate_speed_change_js(
    speed:float  # New playback speed
) -> str:  # JavaScript to update playback speed
    """Generate JS to update Web Audio API playback speed via shared library."""
    return f"""
        if (window.setAlignSpeed) window.setAlignSpeed({speed});
    """

# %% ../../nbs/routes/audio.ipynb #align-audio-init
def init_audio_router(
    state_store:WorkflowStateStore,  # The workflow state store
    workflow_id:str,  # The workflow identifier
    prefix:str,  # Base prefix for audio routes
    urls:AlignmentUrls,  # URL bundle to populate
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, routes dict)
    """Initialize alignment audio control routes."""
    router = APIRouter(prefix=prefix)
    routes = {}

    @router.post("/toggle_auto_nav")
    async def toggle_auto_nav(request, sess):
        """Handle auto-navigate toggle."""
        session_id = get_session_id(sess)
        form_data = await request.form()
        auto_navigate = "auto_navigate" in form_data

        _update_alignment_state(
            state_store, workflow_id, session_id,
            auto_navigate=auto_navigate
        )

        return Script(_generate_auto_nav_js(auto_navigate))

    routes["toggle_auto_nav"] = toggle_auto_nav

    @router.post("/speed_change")
    def speed_change(request, sess, speed:float):
        """Handle playback speed change."""
        session_id = get_session_id(sess)

        _update_alignment_state(
            state_store, workflow_id, session_id,
            playback_speed=speed,
        )

        return Script(_generate_speed_change_js(speed))

    routes["speed_change"] = speed_change

    return router, routes
