"""Alignment state context, getters, and updaters for route handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/core.ipynb.

# %% auto #0
__all__ = ['WorkflowStateStore', 'DEBUG_ALIGN_STATE', 'AlignContext']

# %% ../../nbs/routes/core.ipynb #align-rc-imports
from typing import Any, Dict, List, Optional, NamedTuple

from cjm_fasthtml_interactions.core.state_store import get_session_id
from cjm_fasthtml_card_stack.core.models import CardStackState
from cjm_workflow_state.state_store import SQLiteWorkflowStateStore

from cjm_transcript_vad_align.models import (
    VADChunk, AlignmentStepState
)

# Type alias for state store (duck-typed, accepts any implementation with get_state/update_state)
WorkflowStateStore = SQLiteWorkflowStateStore

# Debug flag for alignment state tracing (set False in production)
DEBUG_ALIGN_STATE = False

# %% ../../nbs/routes/core.ipynb #align-rc-ctx
class AlignContext(NamedTuple):
    """Common alignment state values loaded by handlers."""
    chunk_dicts: List[Dict[str, Any]]  # Serialized VAD chunks
    focused_chunk_index: int  # Currently focused VAD chunk index
    visible_count: int  # Number of visible cards in viewport
    is_auto_mode: bool  # Whether card count is in auto-adjust mode
    card_width: int  # Card stack width in rem
    media_path: Optional[str]  # Path to original audio file
    audio_duration: Optional[float]  # Total audio duration

# %% ../../nbs/routes/core.ipynb #align-rc-state
def _get_alignment_state(
    state_store:WorkflowStateStore,  # The workflow state store
    workflow_id:str,  # The workflow identifier
    session_id:str,  # Session identifier
) -> AlignmentStepState:  # Typed alignment step state
    """Get the alignment step state from the workflow state store."""
    state = state_store.get_state(workflow_id, session_id)
    step_states = state.get("step_states", {})
    return step_states.get("alignment", {})

def _get_selection_state(
    state_store:WorkflowStateStore,  # The workflow state store
    workflow_id:str,  # The workflow identifier
    session_id:str,  # Session identifier
) -> Dict[str, Any]:  # Selection step state dictionary
    """Get the selection step state (Phase 1) from the workflow state store."""
    state = state_store.get_state(workflow_id, session_id)
    step_states = state.get("step_states", {})
    return step_states.get("selection", {})

def _load_alignment_context(
    state_store:WorkflowStateStore,  # The workflow state store
    workflow_id:str,  # The workflow identifier
    session_id:str,  # Session identifier
) -> AlignContext:  # Loaded context with all common alignment state
    """Load commonly-needed alignment state values in a single call."""
    state = _get_alignment_state(state_store, workflow_id, session_id)
    return AlignContext(
        chunk_dicts=state.get("vad_chunks", []),
        focused_chunk_index=state.get("focused_chunk_index", 0),
        visible_count=state.get("visible_count", 5),
        is_auto_mode=state.get("is_auto_mode", False),
        card_width=state.get("card_width", 40),
        media_path=state.get("media_path"),
        audio_duration=state.get("audio_duration"),
    )

def _update_alignment_state(
    state_store:WorkflowStateStore,  # The workflow state store
    workflow_id:str,  # The workflow identifier
    session_id:str,  # Session identifier
    vad_chunks=None,  # Updated VAD chunks (serialized)
    focused_chunk_index=None,  # Updated focused chunk index
    is_initialized=None,  # Initialization flag
    visible_count=None,  # Visible card count
    is_auto_mode=None,  # Auto-adjust mode flag
    card_width=None,  # Card stack width in rem
    media_path=None,  # Original audio file path
    audio_duration=None,  # Audio duration
) -> None:
    """Update the alignment step state in the workflow state store."""
    if DEBUG_ALIGN_STATE:
        print(f"[ALIGN_STATE] _update_alignment_state called")

    # Read full state to preserve sibling step states
    workflow_state = state_store.get_state(workflow_id, session_id)

    if DEBUG_ALIGN_STATE:
        print(f"[ALIGN_STATE] BEFORE: step_states keys = {list(workflow_state.get('step_states', {}).keys())}")
        selection_state = workflow_state.get('step_states', {}).get('selection', {})
        print(f"[ALIGN_STATE] BEFORE: selection.selected_sources count = {len(selection_state.get('selected_sources', []))}")

    step_states = workflow_state.get("step_states", {})
    align_state = step_states.get("alignment", {})

    # Update only provided fields
    if vad_chunks is not None:
        align_state["vad_chunks"] = vad_chunks
    if focused_chunk_index is not None:
        align_state["focused_chunk_index"] = focused_chunk_index
    if is_initialized is not None:
        align_state["is_initialized"] = is_initialized
    if visible_count is not None:
        align_state["visible_count"] = visible_count
    if is_auto_mode is not None:
        align_state["is_auto_mode"] = is_auto_mode
    if card_width is not None:
        align_state["card_width"] = card_width
    if media_path is not None:
        align_state["media_path"] = media_path
    if audio_duration is not None:
        align_state["audio_duration"] = audio_duration

    step_states["alignment"] = align_state
    workflow_state["step_states"] = step_states

    if DEBUG_ALIGN_STATE:
        print(f"[ALIGN_STATE] AFTER: step_states keys = {list(step_states.keys())}")

    state_store.update_state(workflow_id, session_id, workflow_state)

    if DEBUG_ALIGN_STATE:
        verify_state = state_store.get_state(workflow_id, session_id)
        print(f"[ALIGN_STATE] VERIFY: step_states keys = {list(verify_state.get('step_states', {}).keys())}")

# %% ../../nbs/routes/core.ipynb #align-rc-conversion
def _to_vad_chunks(
    chunk_dicts:List[Dict[str, Any]]  # Serialized VAD chunk dictionaries
) -> List[VADChunk]:  # List of VADChunk objects
    """Convert chunk dictionaries to VADChunk objects."""
    return [VADChunk.from_dict(c) for c in chunk_dicts]

def _build_card_stack_state(
    ctx:AlignContext,  # Loaded alignment context
    active_mode:str=None,  # Current interaction mode name (unused for alignment)
) -> CardStackState:  # Card stack state for library functions
    """Build a CardStackState from alignment context for library functions."""
    return CardStackState(
        focused_index=ctx.focused_chunk_index,
        visible_count=ctx.visible_count,
        card_width=ctx.card_width,
        active_mode=active_mode,
    )
